<a href="https://colab.research.google.com/github/minjeon99/ESAA/blob/main/ESAA_w1_fri_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 7. Reverse a vector (first element becomes last) (★☆☆)

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [8]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,'\n', Z2)

cmn = np.intersect1d(Z1, Z2)
print(cmn)

[2 1 2 3 9 3 5 6 0 6] 
 [4 9 3 2 8 1 7 7 5 2]
[1 2 3 5 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [16]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # False

print('np.sqrt(-1):', np.sqrt(-1))
print('np.emath.sqrt(-1):', np.emath.sqrt(-1))

False
np.sqrt(-1): nan
np.emath.sqrt(-1): 1j


<ipython-input-16-b738a50a9cd9>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # False
<ipython-input-16-b738a50a9cd9>:3: RuntimeWarning: invalid value encountered in sqrt
  print('np.sqrt(-1):', np.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [20]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [56]:
A = np.arange(1,4, dtype='float64')
B = np.arange(5,8, dtype='float64')

np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([ -3.,  -8., -15.])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [81]:
A = np.random.uniform(0,10,10)
print('A:\n',A)
A1 = A // 1
print('using "//":', A1)
A2 = A - (A%1)
print('using %:', A2)

A:
 [6.72285948 9.87904962 7.5371038  1.19129537 4.83893087 2.69595439
 5.8080753  4.0651926  2.80528249 5.91460273]
using "//": [6. 9. 7. 1. 4. 2. 5. 4. 2. 5.]
using %: [6. 9. 7. 1. 4. 2. 5. 4. 2. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [90]:
A = np.zeros((5,5)) + np.arange(0,5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [99]:
A = np.random.randint(0,100,10)
print('before:', A)
sorted_A = np.sort(A)
print('after:', sorted_A)

before: [ 9  2 28 41 25 25 60 83 99 45]
after: [ 2  9 25 25 28 41 45 60 83 99]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [113]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print('A:\n', A, '\nB:\n', B)
print('equal:', np.array_equal(A,B))

A:
 [0 1 1 1 1] 
B:
 [1 1 1 0 0]
equal: False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [137]:
cart = np.random.rand(10,2)
print('cartesian coordinates:\n',A)

x = A[:,0]
y = A[:,1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)

polar = np.zeros((10,2))
polar[:,0] = r
polar[:,1] = theta
print('\npolar coordinates:\n',polar)

cartesian coordinates:
 [[0.4945745  0.32584518]
 [0.22233227 0.35337829]
 [0.76845165 0.23949672]
 [0.12619662 0.30304012]
 [0.22179358 0.69843847]
 [0.23238964 0.01727583]
 [0.79762088 0.85502296]
 [0.21726034 0.94389474]
 [0.54412056 0.76895363]
 [0.44768576 0.34031651]]

polar coordinates:
 [[0.592266   0.58256415]
 [0.41750192 1.00920955]
 [0.80490783 0.3021207 ]
 [0.32826651 1.17620232]
 [0.73280877 1.2633116 ]
 [0.23303089 0.07420344]
 [1.16930035 0.82011769]
 [0.96857593 1.34456237]
 [0.94199622 0.9549801 ]
 [0.5623503  0.6499771 ]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [146]:
Z = np.random.rand(10)
print('Z:\n', Z)
max_idx = Z.argmax()
print('\nmax index:', max_idx)
Z[max_idx] = 0
print('\nreplace:\n', Z)

Z:
 [0.12425871 0.63527407 0.43143822 0.48240145 0.6757524  0.6801152
 0.87710723 0.49673255 0.17387901 0.8380736 ]

max index: 6

replace:
 [0.12425871 0.63527407 0.43143822 0.48240145 0.6757524  0.6801152
 0.         0.49673255 0.17387901 0.8380736 ]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [167]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print('v:', v)

dist = np.abs(Z - v)
min_idx = dist.argmin()
print('clsest value:', Z[min_idx])

v: 94.71796666761514
clsest value: 95


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [184]:
Z = np.arange(9).reshape(3,3)

print('using ndenumerate():')
for i in np.ndenumerate(Z):
  print(i)

print('using ndindex():')
for i in np.ndindex(Z.shape):
  print(i, Z[i])

using ndenumerate():
((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((1, 0), 3)
((1, 1), 4)
((1, 2), 5)
((2, 0), 6)
((2, 1), 7)
((2, 2), 8)
using ndindex():
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [191]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 94)
print(Z)

[[ 0.  0.  0.]
 [ 0.  0. 94.]
 [ 0. 94.  0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [218]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[7 9 1]
 [1 8 4]
 [8 5 5]]


In [240]:
# column 0
print(Z)
s_0 = Z[:,0].argsort()
Z0 = Z[s_0]
print('sorted by column 0:\n',Z0)

[[1 0 2]
 [0 9 9]
 [8 7 3]]
sorted by column 0:
 [[0 9 9]
 [1 0 2]
 [8 7 3]]


In [242]:
# column 1
print(Z)
s_1 = Z[:,1].argsort()
Z1 = Z[s_1]
print('sorted by column 1:\n',Z1)

[[1 0 2]
 [0 9 9]
 [8 7 3]]
sorted by column 1:
 [[1 0 2]
 [8 7 3]
 [0 9 9]]


In [243]:
# column 2
print(Z)
s_2 = Z[:,2].argsort()
Z2 = Z[s_2]
print('sorted by column 1:\n',Z2)

[[1 0 2]
 [0 9 9]
 [8 7 3]]
sorted by column 1:
 [[1 0 2]
 [8 7 3]
 [0 9 9]]
