<a href="https://colab.research.google.com/github/minjeon99/ESAA/blob/Week1/fri_ex1~25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
A = np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
A = np.zeros((5,5))
print("%d bytes" % (A.size * A.itemsize))
print("%d bytes" % A.nbytes)

200 bytes
200 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
A = np.zeros(10)
A[4] =1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
A = A[::-1]
print(A)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr1 = np.arange(0,9)
arr2 = arr1.reshape(3,3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr3 = np.array([1,2,0,0,4,0])
np.nonzero(arr3)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
imatrix = np.eye(3)
print(imatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
rarray = np.random.random((3,3,3))
print(rarray)

[[[0.98195168 0.03511072 0.04138552]
  [0.79956725 0.47049984 0.89795285]
  [0.60683044 0.20132176 0.75472442]]

 [[0.71685371 0.13199485 0.80880387]
  [0.79676037 0.37091778 0.73414772]
  [0.34440138 0.37828114 0.23439404]]

 [[0.54401164 0.29542944 0.84363467]
  [0.4926844  0.11107723 0.28981726]
  [0.73643003 0.30478232 0.09938687]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array2 = np.random.random((10,10))
print(array2)
min = np.min(array2)
max = np.max(array2)
print(min)
print(max)

[[0.41089608 0.75433269 0.04356319 0.07810315 0.12524916 0.17640575
  0.65246788 0.99843676 0.80211986 0.14082414]
 [0.31776627 0.48021263 0.39943517 0.88012184 0.67544241 0.7149163
  0.64002713 0.97930656 0.14230504 0.60138314]
 [0.79386443 0.56936368 0.38958175 0.71046052 0.41934405 0.22503071
  0.99356329 0.19031334 0.78590055 0.07051254]
 [0.39397281 0.23417129 0.76311313 0.40115714 0.49500234 0.4037111
  0.98930888 0.61432876 0.62898577 0.89701153]
 [0.38881168 0.74833113 0.48315975 0.96380814 0.467416   0.09298772
  0.92645666 0.15876877 0.56905916 0.95867127]
 [0.25698703 0.60703909 0.43028802 0.29175964 0.77726414 0.92709173
  0.79008571 0.91305236 0.26604554 0.0494798 ]
 [0.25551333 0.10969714 0.83799557 0.40410358 0.44912358 0.60945046
  0.79185533 0.99566818 0.99833779 0.49958636]
 [0.07203618 0.38444478 0.5536956  0.03006879 0.563073   0.52873021
  0.31561581 0.93842194 0.63878793 0.3525405 ]
 [0.84035598 0.17158368 0.92578362 0.76206904 0.55568127 0.57337782
  0.28926892 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
vector = np.random.random(30)
print(vector)
mean = np.mean(vector)
print(mean)

[0.09281974 0.00418597 0.41054409 0.54460568 0.80664581 0.09076179
 0.41380945 0.14793946 0.47962756 0.11472906 0.30964737 0.48240722
 0.67256895 0.48955364 0.96781539 0.00712213 0.21764235 0.12084933
 0.08971951 0.16945405 0.17046372 0.03523522 0.41714882 0.20792385
 0.31294669 0.82238468 0.73349466 0.9908066  0.9463667  0.43672199]
0.39019804995741736


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr_14 = np.ones((5,5))
arr_14[1:-1,1:-1] = 0
print(arr_14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
# nan

nan

In [ ]:
np.nan == np.nan
# False

False

In [ ]:
np.inf > np.nan
# False

False

In [ ]:
np.nan - np.nan
# nan

nan

In [ ]:
np.nan in set([np.nan])
# True

True

In [ ]:
0.3 == 3 * 0.1
# False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
arr_16 = np.zeros((5,5))
arr_16[1,0] = 1
arr_16[2,1] = 2
arr_16[3,2] = 3
arr_16[4,3] = 4
print(arr_16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


- np.diag() 사용

In [ ]:
arr_16_1 = np.diag([1,2,3,4], k=-1)
print(arr_16_1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
arr_17 = np.zeros((8,8))
evens = [0,2,4,6]
odds = [1,3,5,7]
for i in odds:
  arr_17[i, odds] = 1
for j in evens:
  arr_17[j, evens] = 1
print(arr_17)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**팬시 인덱싱 사용**
- [A::B]: A부터 B의 step만큼 건너뛰면서 slicing

In [ ]:
arr_17_1 = np.zeros((8,8))
arr_17_1[::2, 1::2] = 1
arr_17_1[1::2, ::2] = 1
print(arr_17_1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**np.tile() 사용**

In [ ]:
arr_17_2 = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(arr_17_2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
import random

arr_19 = np.random.random((5,5))
arr_mean = np.mean(arr_19)
arr_std = np.std(arr_19)
arr_norm = (arr_19-arr_mean)/arr_std

print(arr_norm)
print('평균:', np.mean(arr_norm),'\n표준편차:', np.std(arr_norm))

[[-0.54357648 -1.31892262  0.66955123 -0.68207209 -1.37779722]
 [-0.08805139 -0.00572896  0.58618989 -0.00378892  0.85579058]
 [-0.58062589  1.12587954 -0.42064317  1.04197172  1.09276171]
 [ 0.96602315  0.97274757 -1.63933541  1.24783627  1.07605409]
 [ 0.89446227 -1.51110129 -0.89955206 -1.90596054  0.44788802]]
평균: 1.3322676295501878e-17 
표준편차: 0.9999999999999998


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
dot_product = np.dot(a,b)
print(dot_product)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.arange(10)
a[3:9] *= -1
print(a)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A,"\n")
print(np.sum(A,-1))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[ 3 12 21]


- python의 sum은 sum(sequence[,start]) python의 내장함수
- -1+1+2+3+4=9
- numpy.sum(a, axis=None),axis 축으로 더한다.

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# Z<Z>Z

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-10-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-10-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-10-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
