<a href="https://colab.research.google.com/github/minjeon99/ESAA/blob/Week1/fri_ex26~39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [2]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,'\n', Z2)

cmn = np.intersect1d(Z1, Z2)
print(cmn)

[2 1 2 3 9 3 5 6 0 6] 
 [4 9 3 2 8 1 7 7 5 2]
[1 2 3 5 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) # False

print('np.sqrt(-1):', np.sqrt(-1))
print('np.emath.sqrt(-1):', np.emath.sqrt(-1))

False
np.sqrt(-1): nan
np.emath.sqrt(-1): 1j


<ipython-input-16-b738a50a9cd9>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) # False
<ipython-input-16-b738a50a9cd9>:3: RuntimeWarning: invalid value encountered in sqrt
  print('np.sqrt(-1):', np.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.arange(1,4, dtype='float64')
B = np.arange(5,8, dtype='float64')

np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([ -3.,  -8., -15.])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
A = np.random.uniform(0,10,10)
print('A:\n',A)
A1 = A // 1
print('using "//":', A1)
A2 = A - (A%1)
print('using %:', A2)

A:
 [6.72285948 9.87904962 7.5371038  1.19129537 4.83893087 2.69595439
 5.8080753  4.0651926  2.80528249 5.91460273]
using "//": [6. 9. 7. 1. 4. 2. 5. 4. 2. 5.]
using %: [6. 9. 7. 1. 4. 2. 5. 4. 2. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.zeros((5,5)) + np.arange(0,5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
A = np.random.randint(0,100,10)
print('before:', A)
sorted_A = np.sort(A)
print('after:', sorted_A)

before: [ 9  2 28 41 25 25 60 83 99 45]
after: [ 2  9 25 25 28 41 45 60 83 99]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [3]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print('A:\n', A, '\nB:\n', B)
print('equal:', np.array_equal(A,B))

A:
 [0 0 1 0 1] 
B:
 [0 0 1 0 1]
equal: True


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [5]:
A = np.random.random((10,2))
x = A[:,0]
y = A[:,1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
print('R: \n', r)
print('Theta: \n', theta)

R: 
 [0.38493868 1.18960546 0.82009659 0.91673118 0.89797404 0.71862454
 0.79615605 0.86466401 0.60471855 1.16873599]
Theta: 
 [0.70567603 0.82865326 0.94411077 0.29926992 1.01221483 0.33874366
 0.84189744 1.24445678 0.96331406 0.59680536]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [6]:
Z = np.random.random(10)
print('Z:\n', Z)

Z[Z.argmax()] = 0
print('\nreplace:\n', Z)

Z:
 [0.44217265 0.65679139 0.64007155 0.38099952 0.67734396 0.18248989
 0.28124595 0.08031307 0.27791878 0.36749723]

replace:
 [0.44217265 0.65679139 0.64007155 0.38099952 0.         0.18248989
 0.28124595 0.08031307 0.27791878 0.36749723]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [7]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print('v:', v)

min_idx = np.abs(Z - v).argmin()
print('clsest value:', Z[min_idx])

v: 93.2220650662884
clsest value: 93


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [8]:
Z = np.arange(9).reshape(3,3)

print('using ndenumerate():')
for idx, v in np.ndenumerate(Z):
  print(idx, v)

print('using ndindex():')
for i in np.ndindex(Z.shape):
  print(i, Z[i])

using ndenumerate():
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
using ndindex():
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 9)
print(Z)

[[ 0.  0.  0.]
 [ 0.  0. 94.]
 [ 0. 94.  0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [9]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[6 9 0]
 [3 4 6]
 [7 8 5]]


In [10]:
# column 0
Z0 = Z[Z[:,0].argsort()]
print('sorted by column 0:\n',Z0)

sorted by column 0:
 [[3 4 6]
 [6 9 0]
 [7 8 5]]


In [11]:
# column 1
Z1 = Z[Z[:,1].argsort()]
print('sorted by column 1:\n',Z1)

sorted by column 1:
 [[3 4 6]
 [7 8 5]
 [6 9 0]]


In [12]:
# column 2
Z2 = Z[Z[:,2].argsort()]
print('sorted by column 1:\n',Z2)

sorted by column 1:
 [[6 9 0]
 [7 8 5]
 [3 4 6]]
